# Generated by Django 4.1.5 on 2023-01-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_addproductmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='webapp/static')),
                ('pname', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
