# Generated by Django 4.1.5 on 2023-01-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='image',
            field=models.ImageField(upload_to='mapp/static'),
        ),
    ]
