# Generated by Django 4.1.5 on 2023-01-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0006_alter_paymentmodel_paymode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
